### ISSUE TITLE
[BUG] Unable to install ZLS for version `master`

### ISSUE THREAD

**Issue by dylanlangston** [tristanisham/zvm#103]
**Describe the bug**
Hello! As per the title, I'm having trouble installing ZLS when I specify the version as `master`. Getting the following error:
```bash
ERRO invalid version map format: unexpected end of JSON input
```

**To Reproduce**
1. Run `zvm install --zls master`
2. See error

**Expected behavior**
Should install a compatible ZLS version.

**Screenshots**
![image](https://github.com/user-attachments/assets/2495b66a-4a5a-4125-aa18-27232de90c11)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Architecture: x86_64
 - Version: ZVM version v0.7.7 linux/amd64

**Configuration:**
 - VMU: default

**Additional context**
This error does not occur if I install a tagged version using `zvm install --zls 0.13.0`.

**Comment by no-realm** [comment]
Yes, this is an issue with the changes made to the “base url” after #102 got merged. I personally think that @tristanisham  uploaded the wrong binaries, since the version tag points to a commit before those changes were made.

**Comment by tristanisham** [comment]
Yeah, it was probably me. I was trying to bring the base URL in line with the Zig VMU style. I was editing late at night so I'll take the blame for that mistake. 

I did push to the commit before I had decided to update some of the binary function. Namely, I don't like adding new commands to the program unless they're strictly necessary. I should really put that in the contributors document. 

Long story short, I'll take a look at it.

**Comment by tristanisham** [comment]
@dylanlangston @no-realm Fixed in v0.7.8 https://github.com/tristanisham/zvm/releases/tag/v0.7.8

**Comment by no-realm** [comment]
@tristanisham no worries.
btw, i just tested the new version and there is now a different problem 😅 

setting the zls vmu via the `settings` command: `s.ZlsVMU = "https://releases.zigtools.org/"`
tagged zls version index url: `cleanURL(versionMapUrl + "v1/zls/index.json")`
zls select-version url: `(fmt.Sprintf("%s/v1/zls/select-version?[..]`

the *select-version* function expects *no* trailing slash, while the tagged url does expect one, leading to an error no matter what. current workaround is to completely remove the `zlsVersionMapUrl` setting from the `settings.json`.

**Comment by tristanisham** [comment]
Shit. I took out the cleanURL function for a debug test and forgot to add it back in. Looks like 7.9 is coming out today

**Comment by tristanisham** [comment]
This should be fixed in https://github.com/tristanisham/zvm/releases/tag/v0.7.9
