### ISSUE TITLE
Discordant ZVM versions

### ISSUE THREAD

**Issue by antlanc7** [tristanisham/zvm#13]
With the latest version the version shown with `zvm -v` is `v0.1.7`, whereas in the cli help and in the user agent of the download request in the Install function the version is `v0.1.6`.

**Comment by tristanisham** [comment]
Oops, that is certainly a mistake on my end. We'll update with the next version. Try reinstalling the compiled 0.1.7 release. I believe I updated the binaries without a fix late last night?

**Comment by tristanisham** [comment]
@antlanc7 This issue was just addressed in v0.2.0 https://github.com/tristanisham/zvm/releases/tag/v0.2.0
