### ISSUE TITLE
Add build instructions for Windows or release pre-compiled binaries for it.

### ISSUE THREAD

**Issue by danyildiabin** [tristanisham/zvm#2]
Title says it all. Add instructions about how to compile it on Windows. This includes how or where to install dependencies or adding extra steps in build.zig for windows targets.  
_Pre-compiled releases also would be a great addition for this repo._

**Comment by tristanisham** [comment]
Noted. Spent the night working on making ZVM cross-platform (formerly only for Linux). I think it'll work but I'm dealing with weird Windows-specific issues. I recommend just using it with Linux or WSL for now. But, that might change as soon as the next release!

In the meantime, here's linux-amd64:
[linux-amd64.tar.gz](https://github.com/tristanisham/zvm/files/10054145/linux-amd64.tar.gz)

**Comment by tristanisham** [comment]
@danyildiabin We have Windows binaries now!
