### ISSUE TITLE
Feature Request: List available zig versions for installation 

### ISSUE THREAD

**Issue by felipetesc** [tristanisham/zvm#27]
This feature will allow us to verify what zig versions are available before installing it:

Something like: 
```bash
zvm list 
```
or 
```bash
zvm check
```
or
```bash
zvm versions
```

To me the choice of the cmd does't mather much, only to find what binaries are available to be downloaded

**Comment by tristanisham** [comment]
You can use `zvm ls` for this, no?

**Comment by mlaass** [comment]
> You can use `zvm ls` for this, no?

Actually not, because `zvm ls` only lists installed versions.

Also, I have trouble installing other versions of the current dev release e.g I currently can install master which gives me version  `0.12.0-dev.790+ad6f8e3a5` but for another project, I would like to be able to test version `0.12.0-dev.415+5af5d87ad`.

**Comment by tristanisham** [comment]
@mlaass That is an upcoming feature of ZVM. Currently, it only installs the daily release and stable, but within the month It should support all versions of Zig (starting with 0.12.0-dev-***).

**Comment by tristanisham** [comment]
This feature has been added. Thanks @felipetesc for your patience.

**Comment by felipetesc** [comment]
> This feature has been added. Thanks @felipetesc for your patience.

It's you who should be patient with us when we don't use common sense to understand the nature of open source projects. I can only acknowledge by understanding that with the use of your free time you have improved the library. Library which, have as the mainly beneficiaries ourselves. Thanks!
