### ISSUE TITLE
Using --zls flag gives an error

### ISSUE THREAD

**Issue by dogue** [tristanisham/zvm#29]
Not sure if I'm doing something wrong here, but on a fresh install of ZVM 0.3.0, I'm getting an error trying to use the new `--zls` flag. Below is a paste from my terminal output showing two failed tries with the flag and one successful try without.

```
❯ zvm install 0.10.1 --zls
2023/10/30 22:48:09 FATA unsupported Zig version: "--zls"

❯ zvm install -z 0.10.1
flag provided but not defined: -z
Usage of install:
  -D string
        Specify additional dependencies to install with Zig
        
❯ zvm install 0.10.1
Downloading 0.10.1: 100% |██████████████████████████████████████████████████████████████████████████████████| (42/42 MB, 23 MB/s)
Checking shasum...
Shasums match! 🎉
Extracting bundle...
```

Edit: Went back and read the doc. Using `zvm -D zls <zig version>` works fine. It's just the `--zls/-z` flag (mentioned in the help text) doesn't seem to be getting parsed properly.

**Comment by tristanisham** [comment]
Ah! Thanks @dogue! That's an error with the help text. I removed the `--zls` and `-z` flags! That'll be a v0.3.1 fix!

**Comment by tristanisham** [comment]
I've updated the help message to address this issue @dogue. Please run `zvm upgrade` and let me know if you have any further issues with this release! Thanks for pointing the problem out! Always happy to hear your feedback and see your contributions.

https://github.com/tristanisham/zvm/releases/tag/v0.3.1
