### ISSUE TITLE
Determine a method of download files using native Zig

### ISSUE THREAD

**Issue by tristanisham** [tristanisham/zvm#3]
Currently, ZVM uses a cURL binding which makes it platform exclusive. I'd like to find a native Zig solution so ZVM can be compiled with minimal effort on the end user's part.

**Comment by resolritter** [comment]
This is referring to https://github.com/tristanisham/zvm/blob/909f4f3db936019184ac869e354dcdd1d9ee0e6a/install.sh, correct? In other words, you'd want a cross-platform tool which:

1 - Figures out the host's target

   https://github.com/tristanisham/zvm/blob/909f4f3db936019184ac869e354dcdd1d9ee0e6a/install.sh#L7-L8

2 - Downloads the GitHub release for the host's target (`https://github.com/tristanisham/zvm/releases/latest/download/$PLATFORM`)

   https://github.com/tristanisham/zvm/blob/909f4f3db936019184ac869e354dcdd1d9ee0e6a/install.sh#L26

3 - Extracts it afterwards

   https://github.com/tristanisham/zvm/blob/909f4f3db936019184ac869e354dcdd1d9ee0e6a/install.sh#L27

Is that it? Apologies if I have misunderstood the intent here.

**Comment by tristanisham** [comment]
Zig now has a native http module in the standard library.
