### ISSUE TITLE
Running zvm upgrade fails on Windows

### ISSUE THREAD

**Issue by Skarsh** [tristanisham/zvm#31]
When trying to use the upgrade command it gives the following error:

![image](https://github.com/tristanisham/zvm/assets/12898765/243bd643-69dd-438b-bbcb-37d7c564199c)

Not sure where I can find more detailed information to provide here.

**Comment by tristanisham** [comment]
Thanks @Skarsh! Is this a new issue you're experiencing? Or is this just the first time you've tried `zvm upgrade` on Windows?

**Comment by Skarsh** [comment]
This is the first time I've tried `zvm upgrade`, I just started using `zvm` a couple of weeks back.

**Comment by tristanisham** [comment]
This is the first time I've seen this issue. Admittedly, I predominantly develop and test on Linux. I've already made some progress on fixing this issue, and I should hopefully have it updated by the end of the week. In the meantime, you might just have to manually extract and replace `zvm.exe` in `%USERPROFILE%\.zvm\self`, sorry!

**Comment by tristanisham** [comment]
The program accounts for that, as Zig releases are packaged as Zips for
Windows. It’s an issue with access to the temporary file system on
Windows at runtime. Any PRs would be greatly appreciated. 

Tristan Isham

On December 2, 2023, Tristan Isham ***@***.***> wrote:
> I suspect this is because the Windows release archives are .zip
> instead of .tar (as shown on the release page), so no wonder it does
> not have a valid tar header.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/tristanisham/zvm/issues/31#issuecomment-1837118323>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AFQNWUVICIL7M2CRQDGCDDTYHMBV5AVCNFSM6AAAAAA6Z5GOQ2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZXGEYTQMZSGM>.
You are receiving this because you were assigned.Message ID:
***@***.***>

**Comment by antlanc7** [comment]
I also experience this issue, it's not possible at all to upgrade on Windows. 
I've never used Golang so probably I'm not the best person to submit a PR, but it's seems to me that on this line: https://github.com/tristanisham/zvm/blob/2a1638622efa76bfc843d01470e7169329efc466/cli/upgrade.go#L106
it always tries to untar without accounting for the fact that on windows the archive is actually a zip.

**Comment by tristanisham** [comment]
Noted. I'll look into that more later today. I swear that was accounted for 😅. Thanks for finding that!

**Comment by tristanisham** [comment]
I've started to make some updates on `attempt-to-fix-windows-upgrade`. It seems the issue is somewhere in the os.MakeTempDir call? It never gets created on Windows for some reason.

**Comment by tristanisham** [comment]
Okay, so I figured out the issue. It wasn't the temp dir. I stopped clearing it and I realized my path was off.

**Comment by tristanisham** [comment]
So now I just need to figure out a way to update the application while it's running on Windows. Which requires running some secondary script.

**Comment by tristanisham** [comment]
Somewhat fixed. At least for tonight.

**Comment by tristanisham** [comment]
Temporary solution here: https://github.com/tristanisham/zvm/releases/tag/v0.5.5

**Comment by tristanisham** [comment]
Guys. I just fixed it. https://github.com/tristanisham/zvm/releases/tag/v0.6.4 😂 Took me long enough.
