### ISSUE TITLE
`zvm upgrade` failure on ArchLinux

### ISSUE THREAD

**Issue by dogue** [tristanisham/zvm#33]
```
❯ zvm upgrade
There's a new version of ZVM (v0.4.0).
 Run 'zvm upgrade' to install it!
Upgrading ZVM... 100% |██████████████████████████████████████████████████████████████████████████████████████████| (7.5/7.5 MB, 34 MB/s)
2023/11/02 18:52:55 ERRO this is a new command, and may have some issues. Consider reporting your problem on Github :) github=https://github.com/
tristanisham/zvm/issues
2023/11/02 18:52:55 FATA failed to self-upgrade zvm
rename /tmp/zvm-upgrade-2633282309/zvm /home/dogue/.zvm/self/zvm: invalid cross-device link
```

Was on 0.3.0, tried to upgrade and now my zvm installation appears to be broken. The `.zvm` folder is still in place but the shell can't find the actual zvm binary.

Doing a fresh install seems to have worked to repair my install.

**Comment by dogue** [comment]
```
❯ which zvm
/home/dogue/.zvm/self//zvm
```

Binary path, as requested on xitter

**Comment by tristanisham** [comment]
This is similar to the issue on windows after fixing the unzipping issue. Thanks for posting this!

**Comment by TheFunctionalGuy** [comment]
I don't know whether I understand that correctly but for me it doesn't seem like the Windows issue.
On Arch Linux and maybe on other distros `/tmp` is an `tmpfs` mount which resides in memory ([quote](https://wiki.archlinux.org/title/tmpfs)).

`os.Rename` won't work in this case and you need to find another solution for this.

When you already knew that it was failing because of this: just ignore this comment.

**Comment by dogue** [comment]
That appears to be correct. My machine has 32GB and `df` reports `/tmp` as being a 32GB tmpfs.

```
tmpfs            32G  6.5M   32G   1% /tmp
```

**Comment by TheFunctionalGuy** [comment]
I just saw the help wanted label.
What kind of help do you need?

Isn't the solution to simply replace the usage of the `os.Rename` by a function that works over partition boundries?

**Comment by tristanisham** [comment]
I think so? I haven't had time to diagnose this issue fully, thus the _help wanted_ badge. 

What're your applicable solutions?

**Comment by xtexChooser** [comment]
also on openSUSE Tumbleweed

**Comment by darccyy** [comment]
i have this problem too. in my case i have `/` (including `/tmp`) mounted on a separate partition to `/home`

**Comment by tristanisham** [comment]
@xtexChooser @darccyy @dogue Could one of you guys build clone from the most recent master, change the version in `cli/meta/version.go` to something less than the current version and run `ZVM_DEBUG=1 zvm upgrade` and let me know if it works?

I updated the upgrade to now just use `~/.zvm` as the temp dir and updated clean to take care of the upgrade files (It'll call it right after upgrading). It works on my machine, but, ya know.

**Comment by dogue** [comment]
I can as soon as I fix a no-boot condition.

**Comment by dogue** [comment]
```
~/Projects/External/zvm master* 50s
❯ go install .
                                                                                                                                                 
~/Projects/External/zvm master*
❯ zvm version
v0.4.9
                                                                                                                                                 
~/Projects/External/zvm master*
❯ ZVM_DEBUG=1 zvm upgrade
You are on ZVM v0.4.9... upgrading to (v0.5.0)2024/01/30 19:06:27 DEBU exe dir path=/home/dogue/.zvm/self
2024/01/30 19:06:27 DEBU tempDir name=/home/dogue/.zvm/4259791209.tar
Upgrading ZVM... 100% |██████████████████████████████████████████████████████████████████████████████████████████| (8.0/8.0 MB, 37 MB/s)
2024/01/30 19:06:28 DEBU zvmPath path=/home/dogue/.zvm/self/zvm
2024/01/30 19:06:28 DEBU untar tarball=/home/dogue/.zvm/4259791209.tar target=/home/dogue/.zvm/zvm-upgrade-1973702191
                                                                                                                                                 
~/Projects/External/zvm master*
❯
```

**Comment by tristanisham** [comment]
@dogue what version of ZVM do you have installed now (if you just run `zvm version` off the zvm installed on your path?

**Comment by dogue** [comment]
0.5.0 :grin:

**Comment by darccyy** [comment]
i was previously using the AUR version (listed as `0.5.0-1` on the AUR, but `zvm version` returns `v0.4.2`).
i installed v0.4.1 from manually from releases, and it had the same issue.

**Comment by darccyy** [comment]
> Isn't the solution to simply replace the usage of the `os.Rename` by a function that works over partition boundries?

This sounds right to me 😄

**Comment by tristanisham** [comment]
Okay, so it worked correctly. @darccyy could you please try the same thing? You don't have to install zvm like @dogue did. You can just run `go build` and it'll build in the directory. It'll only update the binary it's called from if the install directory envs are changed. Really an option for people who have weird circumstances on their machine.

**Comment by darccyy** [comment]
it seems to have worked😄

**Comment by xtexChooser** [comment]
yeah it worked!

**Comment by dogue** [comment]
> Okay, so it worked correctly. @darccyy could you please try the same thing? You don't have to install zvm like @dogue did. You can just run `go build` and it'll build in the directory. It'll only update the binary it's called from if the install directory envs are changed. Really an option for people who have weird circumstances on their machine. 

Yeah I'm still a Go noob but I removed that version and verified that everything is good in `~/.zvm`

**Comment by tristanisham** [comment]
Thanks @dogue! You really helped me out tonight,

**Comment by tristanisham** [comment]
@xtexChooser Thank you so much for helping out. You helped a ton. All three of you are awesome.
