### ISSUE TITLE
Incorrect ZLS version

### ISSUE THREAD

**Issue by harrylaulau** [tristanisham/zvm#38]
I am on Windows. I have installed zvm properly and ran `zvm i -D=zls master` to install zig and zls. However, `zls --version` gives `0.11.0` while `zig version` gives `0.12.0-dev.2127+fcc0c5ddc`. 

Edit: Current temporary fix - Since I am only using zls on vscode, I have manually downloaded the zls binary from the repo and updated the path inside vscode extension setting instead. It would be nice if the versioning of zls can be controlled directly by zvm while the vscode extension setting points directly to `.zvm\bin`

**Comment by tristanisham** [comment]
Just merged @maxschuele's PR.
