### ISSUE TITLE
--vmu flag set's version map flag in settings, but ZVM still installs from default

### ISSUE THREAD

**Issue by tristanisham** [tristanisham/zvm#42]
Using `zvm -vmu "https://example.com"` correctly sets the value in `~/.zvm/settings.json`. 

```json
{
    "useColor": true,
    "versionMapUrl": "https://example.com"
}
```
But running `zvm i master` resets the setting and fetches from the default. 
```json
{
    "useColor": true,
    "versionMapUrl": "https://ziglang.org/download/index.json"
}
```

I believe the bug is in `ZVM.fetchVersionMap()` near line 20. The call to loadSetting is the logical place for the reset but it doesn't modify the data structure.
```go
func (z *ZVM) loadSettings() error {
	set_path := z.Settings.basePath
	if _, err := os.Stat(set_path); errors.Is(err, os.ErrNotExist) {
		return ErrNoSettings
	}

	data, err := os.ReadFile(set_path)
	if err != nil {
		return err
	}

	return json.Unmarshal(data, &z.Settings)
}
```

Some fresh eyes on this issue would be appreciated as I'm very occupied with life stuff at the moment. @OlshaMB would you please take a look as this is directly related to your pull request?

**Comment by OlshaMB** [comment]
I will try to fix it
