### ISSUE TITLE
Add support for installing Mach builds of Zig

### ISSUE THREAD

**Issue by tristanisham** [tristanisham/zvm#45]
- [Source](https://devlog.hexops.com/2024/announcing-nominated-zig/)

Add ability to install Mach builds of zig. Leading contender for command is `zvm i mach`, but nothing's set in stone.

**Comment by OlshaMB** [comment]
You can install them using this version map: https://machengine.org/zig/index.json
And this command:
`zvm --vmu https://machengine.org/zig/index.json install mach-latest`

**Comment by OlshaMB** [comment]
So there is nothing to implement

**Comment by tristanisham** [comment]
Added a Mach alias to make this easier. Still! That's basically what it does. Thanks for pointing this out.

**Comment by AClon314** [comment]
in zvm v0.7.1, just run this:
```sh
zvm vmu https://machengine.org/zig/index.json
zvm i mach-latest
```
