### ISSUE TITLE
I can't install zvm on Fedora 39 aarch64 (Asahi Linux)

### ISSUE THREAD

**Issue by kkk669** [tristanisham/zvm#52]
I'm using Fedora 39 aarch64, but I can't install zvm.

```console
$ curl https://raw.githubusercontent.com/tristanisham/zvm/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3808  100  3808    0     0   6459      0 --:--:-- --:--:-- --:--:--  6454
Installing zvm-linux-aarch64.tar in /home/kebo/zvm
wget is installed. Using wget...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

Run the following commands to put ZVM on your path via /home/kebo/.profile

echo "# ZVM" >> $HOME/.profile
echo 'export ZVM_INSTALL="$HOME/.zvm/self"' >> $HOME/.profile
echo 'export PATH="$PATH:$HOME/.zvm/bin"' >> $HOME/.profile
echo 'export PATH="$PATH:$ZVM_INSTALL/"' >> $HOME/.profile
Run 'source ~/.profile' to start using ZVM in this shell!
```

It seems that `install.sh` tried to download zvm-linux-aarch64.tar, not [zvm-linux-arm64.tar](https://github.com/tristanisham/zvm/releases/tag/v0.5.5).

**Comment by tristanisham** [comment]
Thanks for reporting! I’ll take a look at this. In the meantime, the instructions in the README should be sufficient to set up a new install.

**Comment by kkk669** [comment]
I'm using [Fedora Asahi Remix](https://docs.fedoraproject.org/en-US/fedora-asahi-remix/), but AFAIK, this is the issue that occurs on all aarch64 Linux, regardless of the ditro. For instance, it also occurs on Ubuntu aarch64.

I found a cause. zvm seems to retrieve a host architecture [here](https://github.com/tristanisham/zvm/blob/88cdf1f0bb816317acf1cc5f0a255b2a6861cbc0/install.sh#L7). However, in Linux, there is `aarch64` but no `arm64` in `uname -m`.

https://stackoverflow.com/a/45125525/1587435

So I think you should rename `zvm-linux-arm64.tar` to `zvm-linux-aarch64.tar` on [a release note](https://github.com/tristanisham/zvm/releases/tag/v0.5.5).
