### ISSUE TITLE
Installing/Using Zig Versions Fails on Windows with ZVM 0.5.5

### ISSUE THREAD

**Issue by Chris3606** [tristanisham/zvm#56]
# Steps Taken
- Install zvm from powershell with: `irm https://raw.githubusercontent.com/tristanisham/zvm/master/install.ps1 | iex`
- run `zvm i -D=zls 0.11.0` (or any other zig version)

# Actual Results
The following error is produced:
```
PS C:\Users\user> zvm i -D=zls 0.11.0
Downloading 0.11.0: 100% |█████████████████████████████████████████████████████████| (77/77 MB, 88 MB/s)
Checking shasum...
Shasums match! 🎉
Extracting bundle...
Removing old symlink
2024/03/01 09:21:13 FATA could not remove bin remove C:\Users\user\.zvm\bin\zvm.exe: Access is denied.="missing value"
```

# Expected Results
I can install zig versions.

# Notes
Best guess is that zvm is trying to point the .zvm/bin directory at the bin directory for the 0.11.0 install, however the zvm executable is also in that directory, and since ZVM is running windows will not allow changing the symlink (Windows keeps file handles open to running processes).  Probably best to _not_ have the zvm executable in a directory that ZVM can modify the symlink for.

**Comment by nithinkjoy-tech** [comment]
@Chris3606 Working on this issue.

@tristanisham Could you please assign this issue to me.
