### ISSUE TITLE
Feat: Windows | Run commands without administrative mode

### ISSUE THREAD

**Issue by nithinkjoy-tech** [tristanisham/zvm#59]
This feature lets us run `zvm install` and `zvm use` command without explicitly opening command prompt in administrative mode in windows machine.

**Comment by nithinkjoy-tech** [comment]
@tristanisham We have 2 functions which needs to be used in `install.go` and `use.go`. Which is the common place to add these functions?

**Comment by nithinkjoy-tech** [comment]
The build is getting failed for machines other than windows when i add `//go:build !linux` flag in `user_perm_win.go`. If I remove that flag then it builds fine.

**Comment by tristanisham** [comment]
Yeah, take off the build tag. I haven't had a chance to review any code.

**Comment by nithinkjoy-tech** [comment]
Yeah sure, Have raised draft PR, will test in my system for all cases and will raise PR.
