### ISSUE TITLE
Error: bus error

### ISSUE THREAD

**Issue by fwx5618177** [tristanisham/zvm#61]
When I use the command `zvm use master`, it mentions this error: `2024/03/07 14:07:17 WARN signal: bus error`

<img width="366" alt="image" src="https://github.com/tristanisham/zvm/assets/25654385/37de049b-c97f-4360-bf6a-35eb35dcf979">

**Comment by tristanisham** [comment]
Hey @fwx5618177 , what operating system and architecture are you on?

**Comment by fwx5618177** [comment]
> Hey @fwx5618177 , what operating system and architecture are you on?

Now use MacOS Big Sur 11.5.2(20G95)

**Comment by tristanisham** [comment]
Are you on Apple Silicon or the old Intel chips?

**Comment by fwx5618177** [comment]
> Are you on Apple Silicon or the old Intel chips?

Yep, I still use M1 silicon.
