### ISSUE TITLE
Limiting Elevated Scripts on Windows

### ISSUE THREAD

**Issue by tristanisham** [tristanisham/zvm#62]
#59 Is there any way to limit the powers of this file to only elevate a limited set of commands? Leaving a generic `elevate.cmd` file siting on a user's system leaves a bad taste in my mouth, @nithinkjoy-tech.

**Comment by tristanisham** [comment]
@nithinkjoy-tech, could you look into how to replace your CMD and VBS scripts with Go code. I'd like for us to have a way to tell if we're running as administrator, and to rerun ourselves as administrators with the user's commands.

**Comment by nithinkjoy-tech** [comment]
@tristanisham I was busy in other works. Sure will check its possibility.

**Comment by nithinkjoy-tech** [comment]
@tristanisham Wow, I saw better solution Implemented by you. It looks cool and awesome. 🤩

**Comment by tristanisham** [comment]
Thanks @nithinkjoy-tech, but I was just building off your excellent pull request. I'd have no idea this was an issue still if not for you. Thanks. 

I was wondering if you'd look over my [alternative implementation](https://github.com/tristanisham/zvm/blob/feature-alternative-win-symlink/cli/meta/symlink_win.go). It seems more powerful but I don't know enough about Windows to be sure it's right.

**Comment by nithinkjoy-tech** [comment]
![image](https://github.com/tristanisham/zvm/assets/62066971/a96d0570-117f-497d-ba7c-7398350fa8b2)
I am getting this error when I run in non-administrative terminal.

**Comment by tristanisham** [comment]
@nithinkjoy-tech Is that on the branch or currently on Master?

**Comment by nithinkjoy-tech** [comment]
@tristanisham Its happening in master aswell as after installing using powershell script.

**Comment by tristanisham** [comment]
@nithinkjoy-tech Can you run it again with `ZVM_DEBUG=1`? That should print a bunch of extra information that'll let us debug where and what's breaking.

**Comment by tristanisham** [comment]
Might be tied to #63

**Comment by nithinkjoy-tech** [comment]
![image](https://github.com/tristanisham/zvm/assets/62066971/816d3a06-76a0-4f17-924e-1a54c4e67596)
Have Set ZVM_DEBUG=1 as env variables.

Are we trying to remove the already removed bin directory?

**Comment by tristanisham** [comment]
Try using the latest release v0.6.5/4 I can't remember, I put so many releases out yesterday. 😂

**Comment by nithinkjoy-tech** [comment]
> Try using the latest release v0.6.5/4 I can't remember, I put so many releases out yesterday. 😂

😂 Will check.

**Comment by nithinkjoy-tech** [comment]
@tristanisham Yeah, v0.6.7 works 🔥

**Comment by nithinkjoy-tech** [comment]
@tristanisham But when installing new version it installs twice, one in normal shell and again in eleveted shell.
![image](https://github.com/tristanisham/zvm/assets/62066971/49662891-bfa4-4c06-80e5-cfae13c051e4)
