### ISSUE TITLE
ZLS not installing for mach nominated versions

### ISSUE THREAD

**Issue by Khitiara** [tristanisham/zvm#68]
Installing mach-latest with `-vmu mach` and `-D=zls` does not install zls for that version. Not sure if metadata on zls versions for mach nominated versions exists but if it does this would be nice to have working

**Comment by tristanisham** [comment]
Thanks for making the issue!

**Comment by tristanisham** [comment]
![image](https://github.com/tristanisham/zvm/assets/23124818/7ef15cf8-6a01-465f-920c-1070c4124fdc)

Something to look into @tristanisham

**Comment by tristanisham** [comment]
I should just add the ability to download a specific version of ZLS. Empty would work as now, but adding a SEMVER to the flag's argument could fetch it separately.

**Comment by Techatrix** [comment]
The [ZLS release-worker](https://github.com/zigtools/release-worker) can be used to query which ZLS version should be installed based on the provided Zig version. See the [/v1/zls/select-version](https://github.com/zigtools/release-worker?tab=readme-ov-file#v1zlsselect-version) request.
