### ISSUE TITLE
[BUG] Windows symlink bug

### ISSUE THREAD

**Issue by fprijate** [tristanisham/zvm#71]
platform Win10
zvm v0.6.1 windows/amd64

after zvm ls
```
2024/04/09 21:59:10 WARN exec: "zig": executable file not found in %PATH%
0.10.1
0.11.0
master
```
The path and env are configured properly,

After zvm use 0.11.0  (or any other version) , there is following error :
```
2024/04/09 21:53:40 ERRO remove C:\Users\francek\.zvm\bin: The system cannot find the file specified.
```
There is actualy no .zvm\bin subdir

**Comment by tristanisham** [comment]
@guidoschmidt Could you please make the small tweaks I requested on your PR? Then it should be all good to merge and release. I'm on my phone right now so I can't code.

**Comment by tristanisham** [comment]
Attempting to fix with the newest release v0.6.2. Could you please upgrade your version of ZVM and tell me if that fixed your issue?

**Comment by tristanisham** [comment]
https://github.com/tristanisham/zvm/releases/tag/v0.6.2

**Comment by guidoschmidt** [comment]
> @guidoschmidt Could you please make the small tweaks I requested on your PR? Then it should be all good to merge and release. I'm on my phone right now so I can't code.

Looks like you already did and merged? Thanks 🙏🏼 also thanks for the detailed explanations, learned a bit more about Go today 🙃

**Comment by tristanisham** [comment]
Try v0.6.4
