### ISSUE TITLE
[BUG] No zls is available for `0.12.0` and `0.11.0`

### ISSUE THREAD

**Issue by glyh** [tristanisham/zvm#80]
**Describe the bug**
No zls is available for `0.12.0` and `0.11.0`

**To Reproduce**
1. Run `zvm install -D=zls 0.12.0`(or use 0.11.0)
2 Run `zvm use 0.12.0`
3. No zls is on path

**Expected behavior**
zls is installed. 

**Desktop (please complete the following information):**
 - OS: `Linux mechrevo 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux`

**Additional Context**

<del>It looks like there's no 0.12.0 release for zls on zls's repo yet. I think we can forward it to 0.11.0 for now? </del>
ZLS 0.12.0 is already released, we still can't fetch it.

**Comment by glyh** [comment]
It seems the fetching mechanism is failing for ZLS? No zls can be fetched with 0.11.0 as well. It's only working for master for me a the moment.

**Comment by tristanisham** [comment]
That tracks. I haven’t been happy with how we pull ZLS for a while. I
need to figure out how to host it myself, or the community needs to find
a more reputable host. 

Don’t worry, added to my priority tasks. Thanks for reporting!

**Comment by tristanisham** [comment]
Okay, idea. If ZVM catches an error with installing ZLS, or if you pass a flag, it could just clone the repository and use your Zig install to build ZLS with your exact Zig version. Might be temporary when I actually have a server

**Comment by glyh** [comment]
Yeah I think that solution could work.

**Comment by tristanisham** [comment]
Tied to #85
