### ISSUE TITLE
install zig in different drive (Fixed)

### ISSUE THREAD

**Issue by jjinkou2** [tristanisham/zvm#82]
**Is your feature request related to a problem? Please describe.**
I'm on windows , zvm give no solution to where to install zig

**Describe the solution you'd like**
i would like zig to be installed to a different drive : D:\Application\zig instead of C:\

**Describe alternatives you've considered**
no alternative

**Comment by tristanisham** [comment]
Hey @jjinkou2 

This should already be possible. If you set the `ZVM_PATH` environment variable to the drive you want, and move your .zvm directory to that folder, the organ should not use that new space. 

Let me know if that doesn't work and we can dive into this further.

**Comment by jjinkou2** [comment]
i try this env var on my linux and it works. i will tested it on my windows station at my office on monday. 

I may be wrong but it seems this env var is not in the documentation here : https://www.zvm.app/reference/how-to-use/

could you add this ?

**Comment by tristanisham** [comment]
I've updated the README and the website. Please let me know if this issue persists on other platforms, otherwise, unless there's anything else I'll close this issue next week.
