### ISSUE TITLE
[BUG] 'no such file or directory' error when attempting to rename zls

### ISSUE THREAD

**Issue by floooh** [tristanisham/zvm#83]
**Describe the bug**

ZVM version `0.7.1 darwin/arm64` shows an error `no such file or directory` when trying to rename ZSL, but the file already exists under the target path:

```
Downloading 0.12.0: 100% |█████████████████████████████████████████████████| (43/43 MB, 2.5 MB/s)                
Checking shasum...
Shasums match! 🎉
Extracting bundle...
Removing old symlink
Successfully installed Zig!
Finding ZLS executable...
Downloading ZLS 100% |███████████████████████████████████████████████████████████| (913/913 kB, 2.2 MB/s)        
Extracting ZLS...
          
  Error   
          
2024/06/08 16:24:47 ERRO rename /Users/floh/.zvm/0.12.0/bin/zls /Users/floh/.zvm/0.12.0/zls: no such file or directory
```

The file `zls` is not under `0.12.0/bin/zls`, but directly under `0.12.0/zls` (so I guess the renaming isn't necessary in the first place?):

```
0.12.0 ➤ pwd                                                                                                                                                       
/Users/floh/.zvm/0.12.0
0.12.0 ➤ ll                                                                                                                                                        
total 356120
-rw-r--r--   1 floh  staff   1.1K Jan  1  1970 LICENSE
-rw-r--r--   1 floh  staff   8.2K Jan  1  1970 README.md
drwxr-xr-x   3 floh  staff    96B Apr 20 10:55 doc
drwxr-xr-x  16 floh  staff   512B Apr 20 10:55 lib
-rwxr-xr-x   1 floh  staff   166M Apr 20 10:55 zig
-rwxr-xr-x   1 floh  staff   3.1M Apr 26 11:36 zls
```

**To Reproduce**
1. on macOS, just run `zvm install --zls 0.12.0`

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Architecture: arm64
 - Version: ZVM version 0.7.1

**Configuration:**
 - all vanilla

**Comment by tristanisham** [comment]
Hey @floooh 

This issue is being worked on in #85. There's a PR I'm planning to merge after some small changes tonight so this issue should be addressed by the end of today. 

Thus, I'm going to close this issue, but I really encourage you to continue the discussion to #85.
