### ISSUE TITLE
[BUG] zvm upgrade crashed

### ISSUE THREAD

**Issue by xiaods** [tristanisham/zvm#84]
**Describe the bug**
run `zvm upgrade` crashed

**To Reproduce**
1. Run `zvm  upgrade`
2. See error below:
```
xiaods@ZBBB2006M-0032 ~/code/build-nfs-ganesha $ zvm version
zvm v0.6.7 linux/amd64
xiaods@ZBBB2006M-0032 ~/code/build-nfs-ganesha $ zvm upgrade
You are on ZVM v0.6.7... upgrading to (v0.7.1)panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x78f575]

goroutine 1 [running]:
github.com/tristanisham/zvm/cli.(*ZVM).Upgrade(0xc000030740)
        github.com/tristanisham/zvm/cli/upgrade.go:74 +0x495
main.main()
        github.com/tristanisham/zvm/main.go:175 +0x756
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu wsl on win10
 - Architecture  x86_64
 - Version v0.6.7

**Configuration:**

**Additional context**

**Comment by tristanisham** [comment]
Huh, that's so weird. Might have already fixed in the latest release. I'd suggest reinstalling ZVM with the install script. Unless you've customized the install location or any of the default environment variables, you should just be able to delete `~/.zvm` and rerun the one liner to upgrade to the new version.

**Comment by xiaods** [comment]
> Huh, that's so weird. Might have already fixed in the latest release. I'd suggest reinstalling ZVM with the install script. Unless you've customized the install location or any of the default environment variables, you should just be able to delete `~/.zvm` and rerun the one liner to upgrade to the new version.

Yes, I have reinstalled the ZVM and manually replaced it.
