### ISSUE TITLE
[BUG] Cannot move zls

### ISSUE THREAD

**Issue by KeithBrown39423** [tristanisham/zvm#85]
**Describe the bug**

**To Reproduce**
1. Run `zvm install --zls 0.12.0`

**Expected behavior**
Install zig 0.12.0 along with zls

**Error report**
```
Extracting ZLS...

  Error

2024/06/14 10:05:15 ERRO rename C:\Users\keith\.zvm\0.12.0\bin\zls.exe C:\Users\keith\.zvm\0.12.0\zls.exe: The system cannot find the path specified.
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture - amd64 / x86_64
 - Version - 11

**Configuration:**
 - Default

**Comment by tristanisham** [comment]
Hey @KeithBrown39423 

I wrote two small proposals that need to be addressed before a merge, but I'll just do them tonight off of your PR if you can't get to it by then.

**Comment by tristanisham** [comment]
Referencing #83, which was about this identical issue and has been closed even though it was the first. More progress has been made on this issue.

**Comment by KeithBrown39423** [comment]
It appears that in 0.11.0 ZLS is stored in a bin directory which makes this more complicated

**Comment by tristanisham** [comment]
We can have a check. If the file existed can move it from bin. If the files are in the root like the new version then we can unbundle using the modern feature.

**Comment by tristanisham** [comment]
We could even just have a recursive crawl since I'm pretty sure ZLS is compiled statically, no?

**Comment by siniarskimar** [comment]
It seems that the layout of the release archive has changed since 0.12.0.

Before merging the PR, I think it's important to consider support for older versions.

ZLS looks like is a static executable so it's safe to just copy it into `bin/`
```
[marcin:~/.zig]% LC_ALL=C ldd zls # ZLS 0.13.0
     not a dynamic executable
[marcin:~/.zig]% LC_ALL=C ldd zls # ZLS 0.12.0
     not a dynamic executable
```

Second option is to determine and choose the layout based on downloaded ZLS version. More future-proof, in case ZLS changes the layout again...

**Comment by tristanisham** [comment]
Okay, I merged the pull request, but let's continue the work here: [zls-hotix](https://github.com/tristanisham/zvm/tree/zls-hotfix)

**Comment by siniarskimar** [comment]
I've implemented recursive search of ZLS in #88. It works but has some flaws right now. It doesn't check whenever a candidate is actually an executable and uses `filepath.Walk` which reads an entire directory tree into memory first.

**Comment by tristanisham** [comment]
@glyh  does this match your issue? I'd like to consolidate all current ZLS errors into this issue if possible.

**Comment by tristanisham** [comment]
Recursive search seems to have worked perfectly. Adding it to new release. If this doesn't solve the issue, we can create a new issue.
