### ISSUE TITLE
Hide upgrade notice after running upgrade

### ISSUE THREAD

**Issue by xtexChooser** [tristanisham/zvm#89]
**Describe the solution you'd like**
When running `zvm upgrade`, don't print the upgrade available notice, as it has no use in this case.

**Comment by tristanisham** [comment]
This is fair. Though with how the command is currently structured it'd require reworking the current upgrade alert mechanism. Let me look into a refactor. Thanks for bringing it to me as an issue.

**Comment by KeithBrown39423** [comment]
I was about to add this same thing as well lol

**Comment by tristanisham** [comment]
This was added in the latest release. Closing.
