### ISSUE TITLE
[BUG] Failed to fetch ZLS if GitHub API rate limit is hit

### ISSUE THREAD

**Issue by chenzhekl** [tristanisham/zvm#97]
**Describe the bug**
If the client hit the rate limit of GitHub API, ZLS installation would fail.

**To Reproduce**
1. Run `zvm install --zls 0.13.0`
2. See error

**Expected behavior**
ZLS downloads and version checks should be irrelevant to the GitHub API rate limit

**Screenshots**

<img width="540" alt="image" src="https://github.com/user-attachments/assets/0c038af1-3e58-46b3-86b8-8e953002eae3">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture x86_64
 - Version 0.7.4

**Configuration:**
 - VMU (Version Map URL) or alias [e.g. default, mach]

**Additional context**

**Comment by tristanisham** [comment]
Okay, thank you for posting this issue! I'll take a look at rectifying this.
